### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ErhangZhang** [sled-group/DANLI#1]
Hello，when I run the evluation,I meet some questions that I don't know how to solve it 
I run 

> python run/run_neural_symbolic.py \
    --eval_name danli_eval
    --benchmark edh
    --split valid_seen
    --num_processes 2
    --num_gpus 2

> Segmentation fault (core dumped)
I don't know if it's because the GPU  memory is too small，I use a 4090.
Please give me some help。

**Comment by 594zyc** [comment]
Can you verify whether the AI2THOR environment can be successfully started or not? `Segmentation fault` does not look like a CUDA error but something related to your system

**Comment by ErhangZhang** [comment]
Yeah,the AI2THOR environment can be started.
And I found through debugging that this error occurred during the creation of runner_config in inference.py. It called dynamically_load_class and encountered an error while importing in dynamicall_load_class. There was no extra error message.
在utils.py的dynamically_load_class函数中
> module = __import__(package_path, fromlist=[class_name])

**Comment by 594zyc** [comment]
`dynamically_load_class` is adopted from the original [TEACh source code](https://github.com/alexa/teach) without any modification. Could you try to clone the original TEACh repo, run the baseline model following the instructions, and see whether the problem still exists or not? 

Btw, which Python version are you using? The code is tested under Python 3.8 and may have problems with python >= 3.9.

**Comment by ErhangZhang** [comment]
OK,I use Python3.8.And now I'm trying to run the teach baseline model.

**Comment by ErhangZhang** [comment]
Hello,I trying to run the teach baseline,and there were no problems when I run it.

**Comment by ErhangZhang** [comment]
Hello,I doubt it's possible that there is an issue with the version and dependencies of the package. While configuring the environment, there were some package conflicts that I modified.
Here's the version of the package I modified:

> clip==1.0=>0.1.0
mmcv==1.7.1=>1.6.0
mmcv-full==1.5.2=>1.7.2
open3d==0.15.2=>0.18.0
pydantic==1.8.2=>1.10.8
spacy==3.2.3=>3.7.4
state==0.1.2dev-r2=>0.1.1.dev0
torch==1.10.0=>1.11.0

**Comment by 594zyc** [comment]
Can you try to print the `package_path` and `class_name` in `dynamically_load_class` to see which package causes the problem?

**Comment by ErhangZhang** [comment]
Yeah,I print the package_path and class_name,and the result is

> teach.inference.neural_symbolic_model      NeuralSymbolicModel

**Comment by 594zyc** [comment]
I cannot reproduce the problem on my side, which has an ubuntu 20.04 OS and an A6000 GPU. What is your OS version? Besides, have you set all the environment variables following the instructions in README?

**Comment by ErhangZhang** [comment]
Hi. I just solved this problem by commenting on some packages that do not need to be imported in the teach.inference.neural_symbolic_model.py file, which is very magical.

**Comment by zhangerhang** [comment]
And I meet some else questions.

> Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/configuration_utils.py", line 596, in _get_config_dict
    resolved_config_file = cached_path(
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/configuration_utils.py", line 596, in _get_config_dict
    resolved_config_file = cached_path(
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/utils/hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/utils/hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/utils/hub.py", line 539, in get_from_cache
    raise FileNotFoundError(
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/utils/hub.py", line 539, in get_from_cache
    raise FileNotFoundError(
FileNotFoundError: Cannot find the requested files in the cached path and outgoing traffic has been disabled. To enable model look-ups and downloads online, set 'local_files_only' to False.
FileNotFoundError: Cannot find the requested files in the cached path and outgoing traffic has been disabled. To enable model look-ups and downloads online, set 'local_files_only' to False.

And 

> Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/erhang/project/DANLI/src/teach/inference/inference_runner_base.py", line 128, in _run
    model = config.model_class(
  File "/home/erhang/project/DANLI/src/teach/inference/inference_runner_base.py", line 128, in _run
    model = config.model_class(
  File "/home/erhang/project/DANLI/src/teach/inference/neural_symbolic_model.py", line 88, in __init__
    self.agent = NeuralSymbolicAgent(args, process_index, logger_)
  File "/home/erhang/project/DANLI/src/teach/inference/neural_symbolic_model.py", line 88, in __init__
    self.agent = NeuralSymbolicAgent(args, process_index, logger_)
  File "/home/erhang/project/DANLI/src/agent/agent_neural_symbolic.py", line 67, in __init__
    self._build()
  File "/home/erhang/project/DANLI/src/agent/agent_neural_symbolic.py", line 67, in __init__
    self._build()
  File "/home/erhang/project/DANLI/src/agent/agent_neural_symbolic.py", line 78, in _build
    self.subgoal_agent = PDDLSubgoalAgent(self.args, self.device, self.logger)
  File "/home/erhang/project/DANLI/src/agent/agent_neural_symbolic.py", line 78, in _build
    self.subgoal_agent = PDDLSubgoalAgent(self.args, self.device, self.logger)
  File "/home/erhang/project/DANLI/src/agent/pddl_subgoal_agent.py", line 12, in __init__
    super().__init__(args, device, logger)
  File "/home/erhang/project/DANLI/src/agent/pddl_subgoal_agent.py", line 12, in __init__
    super().__init__(args, device, logger)
  File "/home/erhang/project/DANLI/src/agent/subgoal_agent.py", line 33, in __init__
    self._load_subgoal_predictor()
  File "/home/erhang/project/DANLI/src/agent/subgoal_agent.py", line 33, in __init__
    self._load_subgoal_predictor()
  File "/home/erhang/project/DANLI/src/agent/subgoal_agent.py", line 58, in _load_subgoal_predictor
    self.sg_predictor = PLModelWrapper.load_from_checkpoint(
  File "/home/erhang/project/DANLI/src/agent/subgoal_agent.py", line 58, in _load_subgoal_predictor
    self.sg_predictor = PLModelWrapper.load_from_checkpoint(
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 198, in _load_model_state
    model = cls(**_cls_kwargs)
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 198, in _load_model_state
    model = cls(**_cls_kwargs)
  File "/home/erhang/project/DANLI/src/model/model/model_plm.py", line 20, in __init__
    self.model = SubgoalPredictor(args, tokenizer)
  File "/home/erhang/project/DANLI/src/model/model/model_plm.py", line 20, in __init__
    self.model = SubgoalPredictor(args, tokenizer)
  File "/home/erhang/project/DANLI/src/model/model/subgoal_predictor.py", line 26, in __init__
    self.model = BartModel(BartConfig.from_pretrained(args.plm_model_name))
  File "/home/erhang/project/DANLI/src/model/model/subgoal_predictor.py", line 26, in __init__
    self.model = BartModel(BartConfig.from_pretrained(args.plm_model_name))
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/configuration_utils.py", line 521, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/configuration_utils.py", line 521, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/configuration_utils.py", line 548, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/configuration_utils.py", line 548, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/configuration_utils.py", line 636, in _get_config_dict
    raise EnvironmentError(
  File "/home/erhang/miniconda3/envs/danli/lib/python3.8/site-packages/transformers/configuration_utils.py", line 636, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load config for 'facebook/bart-large'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'facebook/bart-large' is the correct path to a directory containing a config.json file
OSError: Can't load config for 'facebook/bart-large'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'facebook/bart-large' is the correct path to a directory containing a config.json file

**Comment by 594zyc** [comment]
Glad to hear that the problem is solved :-)
